### ISSUE TITLE
站点的_config.yml 的theme不用填吗？

### ISSUE THREAD

**Issue by koalahl** [Kaijun/hexo-theme-huxblog#1]

**Comment by Kaijun** [comment]
你要是clone我整个project的话 theme那项已经填好了 😄

**Comment by koalahl** [comment]
hi，那么如果只用你这个主题的话，是要把你的theme/huxblog再复制出来，然后站点theme填huxblog吗？

**Comment by Kaijun** [comment]
是的, 如果是把theme扔到你自己的hexo项目里 确实需要这么做, 就和我README里写的一样, 我之所以提供我整个project, 是因为你还需要定制你的_config.yml(加很多项, 具体参考我的_config.yml), 以及需要新建about tags的页面(具体参考我的source文件夹)

我想的是下个版本我只提供theme, 其他操作或者配置我都写README让用户自己手动创建.
