### ISSUE TITLE
Unhandled rejection ReferenceError

### ISSUE THREAD

**Issue by AlanCheen** [Kaijun/hexo-theme-huxblog#14]
Unhandled rejection ReferenceError: /Users/xxxx/themes/huxblog/layout/page.ejs:73
    71|             ">
    72|
 >> 73|                 <%- page.content || body %>
    74|             </div>
    75|     
    76|             <div class="

body is not defined

你好,我把你的项目clone了,然后把huxblog的目录copy到原来的hexo项目里,其他都挺好,但是就是在 

hexo d -g 的时候报错了,请问怎么解决呢/?

万分感谢

**Comment by Kaijun** [comment]
首先你要是直接使用主题的话, 还需要复制 source 文件夹里的各种 page, 以及这个项目的 config 文件

其次, 不知道是不是你之前有 custome page 在 source 文件夹里, 有的话, 要保证自己新建的 page 的内容不为空. 

参考 https://github.com/Kaijun/hexo-theme-huxblog/issues/12#issuecomment-226970985

**Comment by AlanCheen** [comment]
这个我已经解决了 谢谢 因为index.md里的内容为空
