### ISSUE TITLE
keynote 这个怎么玩?

### ISSUE THREAD

**Issue by AlanCheen** [Kaijun/hexo-theme-huxblog#15]
折腾了一晚上 大部分都可以跑通了 想请教一下 keynote这个怎么玩?

不着急回复,有时间看到再回复吧,我也困了想睡觉了~

Have a nice weekend!

非常感谢你所做的!

**Comment by Kaijun** [comment]
keynote 这部分我只是做了移植, 还没有加上scaffolds帮助产生keynote 的模板

需要手动在头部添加 layout: keynote. 具体你可以参照 `source/_posts/js-module-7day.markdown`
```
---
layout:     keynote
title:      "Example Post using Keynote Layout"
subtitle:   "Keynote: JavaScript Modularization Journey"
iframe:     "http://huangxuan.me/js-module-7day/"
date:       2015-07-09
author:     "Hux"
header-img: "post-bg-js-version.jpg"
tags:
    - 前端开发
    - JavaScript
---
```

keynote 本身不通过本主题生成, 需要自己用 reveal.js 等工具生成, 然后部署到 github 或者自己的服务器. 
博客本身是通过 iframe 加载你的外部 keynote 链接

具体效果参照 http://kaijun.rocks/hexo-theme-huxblog/2015/07/09/js-module-7day/

**Comment by AlanCheen** [comment]
好 谢谢
