### ISSUE TITLE
文章的背景图 似乎是会被劫持?

### ISSUE THREAD

**Issue by AlanCheen** [Kaijun/hexo-theme-huxblog#17]
很奇怪 我图片设置的是一张图  但是 发布到github上有时候会变成另外一张图....

<http://yifeiyuan.me/2016/06/21/App%E7%A0%94%E5%8F%91%E5%BD%95%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0/>

**Comment by AlanCheen** [comment]
好像是百度搞的 好奇怪

**Comment by Kaijun** [comment]
我这边看是没有问题, 而且我也不再国内没法测试. 你确定是百度劫持的吗? 
理论上来说不是运营商的行为, 就是浏览器的行为.

**Comment by AlanCheen** [comment]
因为图片有百度字样 我才怀疑是百度搞的-0-
