### ISSUE TITLE
怎么增加归档(archives)页面

### ISSUE THREAD

**Issue by zhengyq** [Kaijun/hexo-theme-huxblog#18]
我在`source`目录下新增了`archives/index.md`，内容如下：
```
---
title: "存档"
description: "一个"
header-img: "img/archives-bg.jpg"
---
```

然后发现指定的title、descritption、题图都没有生效，archive页面和首页一模一样，请问是什么原因？

**Comment by Kaijun** [comment]
Hi,
归档页面理论上应该是一个列表, 罗列出所有文章的标题, 可以按照年份或者标签进行分类. (但是这个页面在这个主题里还没有实现)...
我想询问下你是想实现什么效果, 还是你指的是 draft , 而不是 archive ?

**Comment by zhengyq** [comment]
@Kaijun

**Comment by zhengyq** [comment]
@Kaijun 

我指的是归档页面，不是draft。

我看了下`public`文件夹，已经生成了相应的archive页面，有一个总的`/archive/index.html`，还有按照年份和月份归类的`archive/2015/index.html`以及`archive/2015/06/index.html`。所以我理解，归档页面是hexo默认支持的。

我遇到的问题是我在`archive/index.md`文档中指定了`title`等信息，但是在生成的页面中获取不到。

**Comment by Kaijun** [comment]
@zhengyq hexo 确实默认支持归档页面, 但是前提是layout 里有定义好的archive模板, 这个主题里目前还没有定义好 archive 模板, 所以你可以看到虽然生成了每个月份的页面, 但是实际里面内容是空的.

如果你在`/layout/archive.ejs` 下加一句`<%- list_archives() %>`, 你就会看到 hexo 渲染的 archive 页面

总结就是... archive 页面还没完成, 还需要深度定制下 😄

**Comment by AlanCheen** [comment]
快点开发 😄

**Comment by AlanCheen** [comment]
似乎还不能添加Page？

**Comment by Kaijun** [comment]
@AlanCheen page 的 content 不能为空 一定要有内容

**Comment by AlanCheen** [comment]
好的~谢谢

**Comment by Kaijun** [comment]
9c0f08038939069aa741552201a20c72ce2b04e6 增加了 archive 页面, 
不知道这个样式怎么样, 有什么更好的想法请继续评论 😄
