### ISSUE TITLE
hexo server出现问题

### ISSUE THREAD

**Issue by Solipugids** [Kaijun/hexo-theme-huxblog#19]
当我把_config.yml文件中的root参数修改为"/"之后再运行hexo server，然后在浏览器中输入路径http://localhost:4000，浏览器会自动重新定向到http://localhost:4000/Hexo-Theme-Huxblog而不是http://localhost:4000。这样的链接重定向是错误的，网页显示Cannot GET /Hexo-Theme-Huxblog。不知道是哪个部分出现了问题。

**Comment by Kaijun** [comment]
我这边测试没有问题 
注意 重新启动 hexo serve!
注意 页面缓存(可以用其他浏览器测试下)

**Comment by jerrywdlee** [comment]
[已解决] chrome浏览器缓存的问题，把缓存(chrome说是图片缓存)的那个删了就好了
