### ISSUE TITLE
如何让Page指向一个二级域名

### ISSUE THREAD

**Issue by AlanCheen** [Kaijun/hexo-theme-huxblog#20]
比如 右上角新增一个菜单 Reading 想指向一个 网页链接 可以实现吗？

**Comment by Kaijun** [comment]
只能手动修改主题.

其实也很简单, 在渲染 navbar 的各个菜单标签前后手动加上自己的链接

https://github.com/Kaijun/hexo-theme-huxblog/blob/master/themes/huxblog/layout/_partial/nav.ejs#L28-L35

可以在27行或者36行插入一个
```
<li>
    <a href="foo">Bar</a>
</li>
```

**Comment by AlanCheen** [comment]
谢谢回复！

Kaijun Chen <notifications@github.com>于2016年7月21日周四 下午9:08写道：

**Comment by Kaijun** [comment]
🎉
