### ISSUE TITLE
page页面没有评论功能

### ISSUE THREAD

**Issue by AlanCheen** [Kaijun/hexo-theme-huxblog#22]
about页面里 如果有评论的话 感觉会更好,有计划做吗?

**Comment by Kaijun** [comment]
因为原 blog 是没有的 所以暂不考虑 :) 当然也可以给 page 页面加上 frontmatter 来判断是否开启评论

**Comment by AlanCheen** [comment]
具体怎么做呢?

说到评论 我配置了 disqus_username 属性,但是disqus 却显示不出来(也没有报错)~ 多说到是可以用
好奇怪

**Comment by Kaijun** [comment]
我指的是我这边可以做一个可以控制是否在 page 界面开启评论的功能... 当然目前还没有

disqus 我其实自己都还没有测试过, 我有空注册个账号测试下 😄

**Comment by AlanCheen** [comment]
哈! 
等你发布啊~~~

貌似disqus都挂了

**Comment by Kaijun** [comment]
### 页面评论
我已经加了页面评论功能了,
你可以参考下 about 页面, 在最前面加上 
```
comments: true
```
就可以打开页面的评论功能了, 具体效果参考 http://kaijun.rocks/hexo-theme-huxblog/about/

### Disqus
我试了下 Disqus, 是没有问题的.

1. 创建Disqus 账号
2. 然后在你的账号底下创建一个 site
3. 在这个 site 的设置里加入你的域名为 trusted domain
4. 把这个 site 的 short name 复制到你的 config.yml

**Comment by AlanCheen** [comment]
我看了一下你的about页面 没有disqus诶~~~

Kaijun Chen <notifications@github.com>于2016年8月5日周五 下午7:18写道：

**Comment by Kaijun** [comment]
![screen shot 2016-08-10 at 12 42 40](https://cloud.githubusercontent.com/assets/1693027/17550979/f73d9376-5ef7-11e6-9969-c5fb097e4f11.png)

因为缓存的缘故吗???

**Comment by Kaijun** [comment]
或者有可能是墙的缘故

**Comment by AlanCheen** [comment]
我能访问google呀 -0-

**Comment by AlanCheen** [comment]
咦，居然能看到了-0-！

**Comment by AlanCheen** [comment]
需要先合你代码 才行么？

**Comment by AlanCheen** [comment]
有点麻烦啊~

**Comment by Kaijun** [comment]
你可以只copy past theme 文件夹 😄

**Comment by Kaijun** [comment]
@AlanCheen 不好意思打扰你啦 本来想去你 blog 评论的 发现你 about 页面没有评论入口 😆  
偶然看到你在杭州 不知道方便说下是什么公司吗? 因为最近在找杭州的工作 😄  
当然可以给我发邮件可能更加~~方便~~私密点: kaijun.cn  艾特 gmail.com

**Comment by AlanCheen** [comment]
最近太忙了 一直没时间搞博客 不知你要找什么职位？

**Comment by Kaijun** [comment]
@AlanCheen  Frontend / Node.js 相关

**Comment by AlanCheen** [comment]
我是做 Android 的 前端这块我不是很清楚诶 或者你有什么目标公司我或许可以看看？

Kaijun Chen <notifications@github.com>于2016年8月19日周五 上午12:10写道：

**Comment by Kaijun** [comment]
@AlanCheen 不用太麻烦啦, 我只是想询问下你所在的公司, 因为杭州相对来说选择比较少, 所以想多采集一些比较优良的公司

**Comment by AlanCheen** [comment]
已经发你邮件啦。

**Comment by zhengyq** [comment]
楼主再找前端职位？不知道我在的公司你敢不感兴趣？profile里有 感兴趣的话可以给我发简历 我帮你推荐哈

**Comment by zhengyq** [comment]
@Kaijun 在找杭州的公司？我profile有我公司信息，感兴趣的话可以发邮件给我，我帮你内推哈😄

**Comment by Kaijun** [comment]
@zhengyq 挺感兴趣, 你在主页没有联系方式, 可以的话给我写封邮件, 邮箱在我的主页有 😄

**Comment by AlanCheen** [comment]
咦 蚂蚁缺 Android 吗 哈哈哈
