### ISSUE TITLE
删除了现有的post后，本地无法打开页面【Cannot GET /】

### ISSUE THREAD

**Issue by Here21** [Kaijun/hexo-theme-huxblog#24]
我将```/source/_posts```中的文件全部删除以后，把```/```下的```db.json```也删除了，然后```hexo g;hexo s```打开```localhost:4000```页面只有```Cannot GET /```

没有post会无法正常运行，算是bug吗

**Comment by Kaijun** [comment]
我刚测试了下hexo 默认主题[hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape), 也是一样.
这应该是 hexo 默认行为, 要是没有 posts 的话 就不会生成 post 的 index 页面.

**Comment by Kaijun** [comment]
可以给 hexo 官方提 issue 但是个人认为也比较无关紧要啦, 因为肯定至少要有一篇 blog 的.
