### ISSUE TITLE
文章 Title 前面多个 "#"

### ISSUE THREAD

**Issue by slarkcoder** [Kaijun/hexo-theme-huxblog#28]

**Comment by Kaijun** [comment]
其实这是原主题就有的特性, 自动创建 anchor 方便复制某一个特定章节的链接.
当然你可以手动修改 css, 
或许会考虑是否有控制这项功能的开关. 因为之前也已经有人反映过这个问题啦

**Comment by slarkcoder** [comment]
这个如何修改 CSS 呢？

**Comment by Kaijun** [comment]
不好意思 我刚看了下 其实设置 _config 里的 anchorjs 项为 false 就行了, 就不会有#啦
https://github.com/Kaijun/hexo-theme-huxblog/blob/master/_config.yml#L39

**Comment by slarkcoder** [comment]
非常感谢！
