### ISSUE TITLE
提两个小问题

### ISSUE THREAD

**Issue by hejiaji** [Kaijun/hexo-theme-huxblog#29]
1. 在readme中 “manually create some extra folders in scaffolds for the new pages” 中的 scaffolds 应该改成 source，据我观察scaffolds并没有任何修改。
2. _config.yml 中， sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`，文中描述说使用绝对url，经过测试，这种写法反而不是绝对路径，应该改成img/avatar.jpg

**Comment by Kaijun** [comment]
1. 已经修正
2. 因为 侧边栏头像渲染后的结果是 `root 地址` + `sidebar-avatar 地址`. 在现有的例子的 config 里
```
root: /hexo-theme-huxblog/
sidebar-avatar: /img/avatar.jpg
```
所以不管是带不带`/`,  渲染结果为 `/hexo-theme-huxblog/img/avatar.jpg` 或者 `/hexo-theme-huxblog//img/avatar.jpg`

第二种情况就是目前的渲染结果. 在 Chrome 中还是会被认为是绝对路径. 不知道在其他浏览器中会是什么情况. 因为我私以为都是绝对路径, 所以在 config 里也带上了`/`, 让语义看起来更清晰点. 当然实际上是不带`/`更加标准.

**Comment by hejiaji** [comment]
Ok，感谢解释与说明，棒棒的
