### ISSUE TITLE
重复代码问题

### ISSUE THREAD

**Issue by hejiaji** [Kaijun/hexo-theme-huxblog#30]
about.ejs 引用了 page.ejs

两者都引用了duoshuo 和 disqus 对代码段，意义不明啊，建议删除一处

**Comment by Kaijun** [comment]
Hi, 感谢提出这个问题 😄 

其实 这个 repo 的 layout 结构并不是很完善, 很多地方耦合很严重, 没有很好得分离出重复的部分作为 patial. 因为之前我移植的时候直接按照原来的文件结构移植的. 导致现在维护起来有些许麻烦.

我之前也给原主题作者提了 PR: Huxpro/huxpro.github.io#74, 分离了重复的部分, 但是还没有被 merge.

要是下个版本发布的话, 我再重构整个结构.

**Comment by hejiaji** [comment]
好的～谢谢回答
