### ISSUE TITLE
执行hexo g时报错，不是很懂前端，求助下，谢谢

### ISSUE THREAD

**Issue by fengfanlbc** [Kaijun/hexo-theme-huxblog#31]
Unhandled rejection TypeError: /Users/F-victor/blog/themes/hexo-theme-huxblog/layout/layout.ejs:9

**Comment by Kaijun** [comment]
请问可以贴下具体错误详情吗?

确保 page 或者 post 要有内容. 

https://github.com/Kaijun/hexo-theme-huxblog/issues/14

**Comment by fengfanlbc** [comment]
你好，我是直接把你的主题git到themes/huxblog里然后修改了hexo的配制文件，直接hexo g && hexo s
访问localhost：4000时没有相应的样式如下图所示
<img width="1280" alt="test1" src="https://cloud.githubusercontent.com/assets/15954613/18459709/65d612fc-799e-11e6-9931-01f0be7f5a7c.png">

然后我进入themes/huxblog里使用npm install,然后再hexo g,报错，如下图所示
<img width="1280" alt="test2" src="https://cloud.githubusercontent.com/assets/15954613/18459739/a7b82548-799e-11e6-8b23-4a516ec15e5d.png">
不知道是不是自己设置有问题

**Comment by Kaijun** [comment]
你好 是这样的
首先 进入themes/huxblog里使用npm install 是**错误**的
需要在项目根目录 运行 npm install

再者, 我建议你直接 fork/clone 整个项目, 而不是单独拷贝 huxblog 这个主题.
因为这个项目的 config.plist 做了很大程度上的扩展. 以及 sources 单独添加了 pages

所以正确的做法是: clone 整个项目, 移植你现有的文章 (复制到 _posts 里), 然后修改我的 config, 适配你自己的情况. 这样应该就没问题了
