### ISSUE TITLE
问一下博客tags里面读取所有文章信息是如何实现的?

### ISSUE THREAD

**Issue by hellodigua** [Kaijun/hexo-theme-huxblog#36]
其实我是想用同样的方法在category里同样实现一遍,所以请教一下

**Comment by Kaijun** [comment]
Hi

首先你可以先看一下我生成tag的代码
如果你用ejs的话可以直接照搬
https://github.com/Kaijun/hexo-theme-huxblog/blob/master/themes/huxblog/layout/tags.ejs#L26-L28

其次是这个map方法, 有这个用法是因为hexo使用了[warehouse](https://github.com/tommy351/warehouse)作为数据模型库, 所以具体接口和方法你可以参照这个库。

至于从哪儿得知这个信息的可以参考官网: https://hexo.io/docs/troubleshooting.html#Iterate-Data-Model-on-Jade-or-Swig

**Comment by Kaijun** [comment]
有问题或者需要帮助的话 可以继续评论

**Comment by Kaijun** [comment]
不好意思 我看错问题啦 其实是 https://github.com/Kaijun/hexo-theme-huxblog/blob/master/themes/huxblog/layout/tags.ejs#L33-L59 这一段代码.
具体如何找到tag里包含了post信息, 也是通过调用warehouse model的方法 然后通过打印看到哒

**Comment by hellodigua** [comment]
太感谢po主了，拿来就能用了T_T，等我把我的博客写好了给你看~

**Comment by Kaijun** [comment]
期待！
