### ISSUE TITLE
文章内最右侧会多出一个滚动条

### ISSUE THREAD

**Issue by liuwang** [Kaijun/hexo-theme-huxblog#38]
文章内最右侧会多出一个滚动条

**Comment by Kaijun** [comment]
浏览器滚动条？
截图？

**Comment by liuwang** [comment]
![image](https://cloud.githubusercontent.com/assets/8500203/19595189/4474dde2-97bb-11e6-962d-248d077c89e9.png)

**Comment by liuwang** [comment]
![image](https://cloud.githubusercontent.com/assets/8500203/19595226/653d9ca8-97bb-11e6-84f0-3a46d4d28585.png)

**Comment by liuwang** [comment]
![image](https://cloud.githubusercontent.com/assets/8500203/19595246/7cf8087e-97bb-11e6-884e-cc6be0feb5f0.png)

**Comment by liuwang** [comment]
麻烦作者帮我分析一下这是什么原因，谢谢

**Comment by Kaijun** [comment]
可以提供下博客地址，浏览器，操作系统的信息吗

**Comment by llldar** [comment]
我认为这是一个正常现象，一个滚动条是针对整个网页的，另一个是针对旁边的catalog的
<img width="357" alt="screen shot 2016-10-23 at 1 43 21 pm" src="https://cloud.githubusercontent.com/assets/9290574/19624387/bef1f110-9926-11e6-8cc0-e72f2ba6dca2.png">

**Comment by liuwang** [comment]
作者你好，这是我的博客地址[liuwang.github.io](url)

**Comment by Kaijun** [comment]
@liuwang 你有改动CSS部分吗？ 确保是最新版本吗？
你看下我刚加了个带catalog的 http://kaijun.rocks/hexo-theme-huxblog/2015/04/14/unix-linux-note/，也没有你这种滚动条的情况。。。
不知道你那边有什么改动？

或者。。你也可以改一下 hux-blog.min.css里, 
```article{overflow-x:hidden} ``` -> ```article{overflow:hidden} ```

**Comment by liuwang** [comment]
@Kaijun 哈哈就是这个article{overflow-x:hidden} -> article{overflow:hidden} ，谢谢你，感谢你的耐心解答。终于好啦，不过我没改过css。
