### ISSUE TITLE
当点击文章内部的 tag 时, 跳转到只包含页头和页脚的空白页面

### ISSUE THREAD

**Issue by ehazon** [Kaijun/hexo-theme-huxblog#4]
折腾了一下午, 对比着该主题的原作者[Hux](https://github.com/huxpro )的 Jekyll 源代码, 发现问题出现在布局文件里的 post.ejs 里面

Hux 的 Jekyll 代码 (注意 '#' 号)

`<a class="tag" href="{{ site.baseurl }}/tags/#{{ tag }}" title="{{ tag }}">{{ tag }}</a>`

Kaijun 的 hexo 代码 

`<a class="tag" href="<%= config.root %><%= tag.path %>" title="<%= tag.name %>"><%= tag.name %></a>`

当点击 tag 时 , 发现 URL 里的地址指向了 username.github.io/tags/sometag , 而不是预期的 username.github.io/tags/#sometag 
所以我尝试着添加以下代码

`<a class="tag" href="<%= config.root %>tags/#<% tag.name %>" title="<%= tag.name %>"><%= tag.name %></a>`

Done , 重新编译后问题解决.
稍后奉上人生第一个 pull request

**Comment by Kaijun** [comment]
Thanks! 我移植的时候太粗心拉! 希望你有更多的PR 😄
