### ISSUE TITLE
上传到github样式全部丢失了， 本地运行一切正常

### ISSUE THREAD

**Issue by zhuzhuyang** [Kaijun/hexo-theme-huxblog#43]
![image](https://cloud.githubusercontent.com/assets/24477932/21284868/6868a9b6-c463-11e6-8a4e-bd177d3de4fb.png)

**Comment by Kaijun** [comment]
@zhuzhuyang  需要贴一下你的 config.yml

**Comment by aaronyou** [comment]
@zhuzhuyang 之前我也遇到这个问题，后来把 _config.yml 文件中 URL部分改掉就好了

**Comment by Surflyan** [comment]
同样遇到了这样的问题，改了将URL root 都改为/，上传后样式就可以了，但是本地预览就出问题了。本地预览改好，上传后样式就丢失了。
