### ISSUE TITLE
关于FRIENDS以及导航栏目的两个问题

### ISSUE THREAD

**Issue by KingsRoad** [Kaijun/hexo-theme-huxblog#44]
1. FRIENDS这个特性如果不想使用了，如何关闭呢？
2. 我想增加一个新的导航栏目“SHARE”，并且调整几个已有导航栏目的顺序，该如何实现呢？
如上，谢谢！

**Comment by Kaijun** [comment]
不好意思 比较忙 回晚了

1. config.yml 里把 friends: [] 这**整个**去掉
2. 可以加个page 具体看 [tags](https://github.com/Kaijun/hexo-theme-huxblog/tree/master/source/tags) / [about](https://github.com/Kaijun/hexo-theme-huxblog/tree/master/source/about) 但是目前顺序无法调整

**Comment by KingsRoad** [comment]
@Kaijun 修改成功，太感谢了~
![default](https://cloud.githubusercontent.com/assets/13881983/21837897/ecca450c-d809-11e6-8514-70af2cfde79b.png)
