### ISSUE TITLE
root问题

### ISSUE THREAD

**Issue by terencehyz** [Kaijun/hexo-theme-huxblog#47]
`_config.yml`中的`root: /hexo-theme-huxblog/`改为`root: /`后，在本地无法查看，`localhost:4000`自动跳转`localhost:4000/hexo-theme-huxblog`
这个该怎么解决

**Comment by Kaijun** [comment]
重启服务，刷新页面缓存试试

**Comment by terencehyz** [comment]
清除了一下浏览器的缓存就可以正常显示了
