### ISSUE TITLE
无图片资源

### ISSUE THREAD

**Issue by MarshallMathersIII** [Kaijun/hexo-theme-huxblog#59]
![image](https://user-images.githubusercontent.com/16094782/29204259-8616b3b8-7ea8-11e7-9ba9-606454d5a854.png)

如上图

**Comment by MarshallMathersIII** [comment]
请问作者这个怎么解决，谢谢啦🙏

**Comment by Kaijun** [comment]
可以提供下线上地址/代码库吗？

**Comment by MarshallMathersIII** [comment]
解决了，谢谢啦
