### ISSUE TITLE
When click post bottom tags open a blank pages

### ISSUE THREAD

**Issue by ehazon** [Kaijun/hexo-theme-huxblog#6]
last night i try to fix post head issue , but this time i find bottom have the issue ,  so  try to copy head post tag code

`  <div class="tags">
     <% page.tags.forEach(function(tag){ %>
     <a class="tag" href="<%= config.root %>tags/#<%= tag.name %>" title="<%= tag.name %>"><%=        tag.name %></a>
       <% }) %>
   </div>`

to replace

` <%- list_tags({style: '', class: '', show_count: false, separator: ''}) %> `

另外, 我在自己的blog上基于这个主题, 进行了一些细微的调整:
  
1. 修改了侧边栏的img大小为100%, 整个侧边栏内部居中
2. 博文内部标题栏的排版为居中,  副标题和作者日期靠右
3. 另外准备将上面导航栏改为下滑后自动固定在top

**Comment by Kaijun** [comment]
原主题没有很好的把各个重复的部分剥离 所以经常改了这忘了那.
我给Hux也发了PR Huxpro/huxpro.github.io#74 这样维护起来就比较方便.
下个版本我再好好重构下

**Comment by ehazon** [comment]
是这样, 昨晚一直在改动, 基于这个主题添加了很多很多自己的元素

大致的改动如下:
 1. 给标题添加细微的文字阴影
 2. 增加博文的右侧目录, 用的 Hexo 自带的 TOC 实现
 3. 修改导航栏滚动后自动置顶, 并略微调整导航栏的样式
 4. 修改了侧边栏的IMG为100% , 侧边栏内部居中
 5. POST模板内部的结构略微变更 

目前正准备给将博文的标题添加到导航栏上方居中, 现在的问题是 HEXO 自带的 TOC 点击后指向的标题过于靠近顶部, 导致标题被置顶显示的导航栏给遮挡住
不知该如何解决, 不知阁下有何解决办法吗?

另外 kaijun 要不要再开个新分支 , 我将这些新改动post到上面去 ?

**Comment by Kaijun** [comment]
@ehazon 
博文目录昨天 @LaiLi 从原博客移植了一个JS实现的 8fb9f12e0769fb57f22f4e8b9a40dd074d991a71
你可以看下

你先推到自己的Repo我可以clone看一下

要是改动很大你也可以在Hexo Site提交自己的主题 😄

**Comment by ehazon** [comment]
hi , kaijun 很抱歉这么晚才回复给你, 实际上我的确听取了你的建议, 因为对主题改动较大, 所以在 hexo site 上提交了基于你和hux修改后的主题, 但是我去掉了页脚下的github start 数即时显示,因为我在后台发现该功能在国内加载github请求非常缓慢耗时,还望谅解.
这是我基于阁下修改的主题: [Anisina](https://github.com/ehazon/ehazon.github.io) , 希望你能喜欢 :)

**Comment by Kaijun** [comment]
@ehazon 很棒! 你可以直接提交到site/hexo里, 填上主题信息以及截图

**Comment by ehazon** [comment]
YEAH!! ， 主题已经在hexo上面可以看到了， 刚刚修改了主题的默认代码仓库地址，目前正在等待合并呢，之前的是我的博客地址：ehazon.github.io ，现在切换到一个新的仓库 hexo-themes-Anisina ， 这样和个人博客分开会好一些 ：）
