### ISSUE TITLE
config.yml中sidebar-about-description，不支持html换行代码。

### ISSUE THREAD

**Issue by 77193404** [Kaijun/hexo-theme-huxblog#78]
在配置config.yml文件时，我想让sidebar-about-description参数的内容换行显示。但是输入<br>之后，并不会换行。

**Comment by 77193404** [comment]
输入《br》之后，并不会换行。

**Comment by Kaijun** [comment]
@77193404 https://github.com/Kaijun/hexo-theme-huxblog/blob/3dbc45041d9ef66f80f633a9e69f20261f734717/themes/huxblog/layout/page.ejs#L180

这边的 `<%=` 会 escape 掉 html 的 tag，如果要换行，可以手动替换成 `<%-` 试一下
