### ISSUE TITLE
关于markdown文件生成模版修改问题。

### ISSUE THREAD

**Issue by echohce** [Kaijun/hexo-theme-huxblog#8]
想询问下如何修改使用hexo new <title>命令生成的markdown文件模版

**Comment by Kaijun** [comment]
我不是很清楚你的意思
你指的是 hexo new xxx 生成的markdown 自动带上自定义的front-matter吗

**Comment by echohce** [comment]
嗯，是指的front-matter，找到修改方法了。麻烦了。

**Comment by Kaijun** [comment]
https://hexo.io/docs/writing.html#Scaffolds
😄
