### ISSUE TITLE
layout and format error 

### ISSUE THREAD

**Issue by lcbluestorm** [Kaijun/hexo-theme-huxblog#9]
Running  in local environment is normal.
But, when i replace with my own repo, the format and layout are error( http://lcbluestorm.github.io/)

**Comment by Kaijun** [comment]
Hello
you need also to edit these [two lines](https://github.com/Kaijun/hexo-theme-huxblog/blob/master/_config.yml#L14-L15)

```
url: http://lcbluestorm.github.io
root: /
```

**Comment by Kaijun** [comment]
if the problem still exists, plz re-open 😄
